/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDropdown: typeof import('vant/es')['Dropdown']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanImage: typeof import('vant/es')['Image']
    VanPagination: typeof import('vant/es')['Pagination']
    VanTable: typeof import('vant/es')['Table']
    VanTableColumn: typeof import('vant/es')['TableColumn']
    VantButton: typeof import('vant/es')['tButton']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
